### ISSUE TITLE
uNode 3 not work

### ISSUE THREAD

**Issue by Racot007** [wahidrachmawan/uNode#1]
Unity 2023.2.20 Unode install via git url

This graph does not work at all (no log message or rotation). Maybe I miss something? Preview after hitting compile shows empty start and update functions.

![UNodeNotWork](https://github.com/wahidrachmawan/uNode/assets/6072592/8f4b0109-bcb0-484b-b8c4-3e36093fd8f0)

**Comment by wahidrachmawan** [comment]
Place the Debug inside a Start, and place the Rotate inside a Update function.

Or you can add event node by right click in canvas > Add Event > Start
![image](https://github.com/wahidrachmawan/uNode/assets/4220747/90e17825-785a-4ad1-a9cf-64823fee6cc1)

**Comment by Racot007** [comment]
Thanks. This is work. 
What purpose for start and update nodes that I use?

**Comment by wahidrachmawan** [comment]
You use is to call the start and update function manually.

**Comment by Racot007** [comment]
Understand. Thanks for info
